# Generated by Django 6.0.6 on 2026-06-21 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_chapter', models.CharField(blank=True, max_length=200, verbose_name='Chapitre en cours')),
                ('completed_chapters', models.TextField(blank=True, help_text='Liste ou description des chapitres terminés.', verbose_name='Chapitres terminés')),
                ('percentage', models.PositiveIntegerField(default=0, verbose_name="Pourcentage d'avancement")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.course')),
            ],
        ),
    ]
