# Generated by Django 6.0.6 on 2026-06-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForumReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Réponse')),
                ('file', models.FileField(blank=True, null=True, upload_to='forum_files/', verbose_name='Pièce jointe')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Lien vidéo explicative')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForumThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sujet de discussion')),
                ('content', models.TextField(verbose_name='Question ou message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
