# Generated by Django 6.0.6 on 2026-06-21 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumreply',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Réponses forum'},
        ),
        migrations.AlterModelOptions(
            name='forumthread',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='forumreply',
            name='file',
        ),
        migrations.RemoveField(
            model_name='forumreply',
            name='video_url',
        ),
        migrations.AddField(
            model_name='forumreply',
            name='is_official',
            field=models.BooleanField(default=False, verbose_name='Réponse officielle (professeur)'),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='is_resolved',
            field=models.BooleanField(default=False, verbose_name='Résolu'),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ForumAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='forum/', verbose_name='Document')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Lien vidéo explicative')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='forum.forumreply')),
            ],
        ),
    ]
