# Generated by Django 4.2.30 on 2026-06-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_assignment_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/instructions/', verbose_name='Fichier joint (Consignes)'),
        ),
    ]
